export const MAKE_ORDER_REQUEST = "MAKE_ORDER_REQUEST";
export const MAKE_ORDER_SUCCESS = "MAKE_ORDER_SUCCESS";
export const MAKE_ORDER_FAILURE = "MAKE_ORDER_FAILURE";
export const MAKE_ORDER_RESET = "MAKE_ORDER_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAILURE = "ORDER_DETAILS_FAILURE";

export const USER_ORDER_LIST_REQUEST = "USER_ORDER_LIST_REQUEST";
export const USER_ORDER_LIST_SUCCESS = "USER_ORDER_LIST_SUCCESS";
export const USER_ORDER_LIST_FAILURE = "USER_ORDER_LIST_FAILURE";
export const USER_ORDER_LIST_RESET = "USER_ORDER_LIST_RESET";
